---
- name: installs the unzip package
  yum: name=unzip state=installed

- name: 'make sure sonar packages are installed'
  yum: name={{item}} state=installed
  when: ansible_os_family == "RedHat"
  with_items: "{{sonar_dependencies}}"
  #notify: restart sonar
  
#- name: 'Ensure sonar is running'
#  service: name=sonar state=started
